### ISSUE TITLE
Did suntime change?

### ISSUE THREAD

**Issue by ekstremedia** [SatAgro/suntime#14]
Hi, I cannot run this script:

```
pi@sortlandcam-2:~/raspberry-timelapse $ pip3 install suntime
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting suntime
  Downloading https://files.pythonhosted.org/packages/93/95/a4eec0b36daeda6fa84b804da308211141d4a6ada13da228ecdf49600434/suntime-1.2.5-py3-none-any.whl
Collecting python-dateutil (from suntime)
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil->suntime) (1.12.0)
Installing collected packages: python-dateutil, suntime
Successfully installed python-dateutil-2.8.1 suntime-1.2.5
```

```
pi@sortlandcam-2:~/raspberry-timelapse $ python3 suntime.py
Traceback (most recent call last):
  File "suntime.py", line 2, in <module>
    from suntime import Sun, SunTimeException
  File "/home/pi/raspberry-timelapse/suntime.py", line 2, in <module>
    from suntime import Sun, SunTimeException
ImportError: cannot import name 'Sun' from 'suntime' (/home/pi/raspberry-timelapse/suntime.py)

```

Is this because suntime changed something?

**Comment by kstopa** [comment]
The problem is that you called your script `suntime.py` and your project is loading it as the `suntime` module instead of the library.

**Comment by ekstremedia** [comment]
Thank you so much for explaining that, sir.
